* dmenu-custom
  Run programs and open websites with [[http://tools.suckless.org/dmenu/][dmenu]].
** How does it work?
   1. Show a list of programs (from =/bin=) with dmenu (like normal)
      - Add website names from =~/.dmenu-web= (if that file exists)
   2. After choosing a program:
      1. If it's a website name, open Chromium, if additional search pattern argument is supplied, add it to an url as search pattern
      2. If it's a program listed in =~/.dmenu-terminal=, open it in a terminal
         with =xterm -e $program=.
      3. Otherwise, open it normally.
** The format of =~/.dmenu-web=
#+BEGIN_SRC
# comments start with a # sign at the start of a line
# url,keyword,optional-keyword
https://github.com/,gh,github
# Following google url contains "%s" which is replaced later for search pattern
https://google.com/search?q=%s , google , g
#+END_SRC
  Note: You can have multiple keywords per URL, but you /must/ specify at least
  one.
** The format of =~/.dmenu-terminal=
   Separate full application names (the names of the binaries) with whitespace
   characters.
#+BEGIN_SRC
# comments start with a # sign at the start of a line
# there are three apps listed (spaces or newlines to separate them
vim
cmus tmux
#+END_SRC
** Hooking it up to XMonad
  It's easy to run this from XMonad, here's how I do it:
#+BEGIN_SRC haskell
import XMonad
import XMonad.Util.EZConfig

main = xmonad $ defaultConfig
        `additionalKeysP`
        [ ("M-p" , spawn '"$HOME/.bin/dmenu-custom"') ]
#+END_SRC
** See also
   This is based off of (and replaces) [[https://github.com/losingkeys/dmenu-terminal][dmenu-terminal]] and [[https://github.com/losingkeys/dmenu-web][dmenu-web]].
